# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nguyen Tien Hung
title: Student
email: nguyentienhung.quynhon@gmail.com
# email_title: Email (Email title override)
phone: (+84) 915 730 264
# phone_title: Phone (Phone title override)
website: https://thepotatohasnoname.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  thepotatohasnoname
facebook_username: t.hunggg
linkedin_username: ngtienhung14

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-2427629321"
gtag: "G-QXEWM58P0R"
google_analytics: "G-QXEWM58P0R"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/hungnguyen.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm currently a student of University of Information Technology - Vietnam National University HCMC. Major in Computer Science.

content:
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: University of Information Technology - Vietnam National University HCMC
        sub_title: BSc, Computer Science
        caption: 2020 - 2024
        caption: >
         UIT is a university member of Vietnam National University of Ho Chi Minh City (VNUHCM), UIT takes charge of training high-ranked labor force in information technology (IT), who are to contribute to the development of Vietnam's IT industry.
        description: | # this will include new lines to allow paragraphs
          I'm working hard to achieve knowledge in Computer Science and its related fields.
      - layout: top-left
        title: Le Quy Don Highschool for the Gifted
        sub_title: Informatics
        caption: 2017 - 2020
        caption: >
         My highschool, which is focus on Informatics
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I'm a sociable person who can be very easy to work with. I have strong enthusiasm to research many interesting things in many fields of life, especially in Computer Science.
      Though my general profile in Computer Science is not really nice at the moment, but I'm doing my best to get more knowledge in this field.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
